name: Build Docker
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    container: 
        image: sglahn/platformio-core:latest
        volumes:
            - $GITHUB_WORKSPACE:/workspace

    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: Build
        run: platformio run
        working-directory: ./firmware/V1.2/Marlin-2.0.x-SKR-Mini-E3-V1.2/

      #- name: Upload Artifacts 
        #uses: actions/upload-artifact@v1
        #with:
          #name: firmwaredir
          #path: ./firmware/V1.2/Marlin-2.0.x-SKR-Mini-E3-V1.2/.pio/build/STM32F103RC_bigtree_512K/firmware.bin


#sglahn/platformio-core:latest
